image: "juliacomputing/juliapro:v1.4.2-1"

variables:
  JULIA_PKG_SERVER: pumas.juliateam.io
  PRIVATE_REGISTRY_NAME: PumasRegistry
  PRIVATE_REGISTRY_UUID: 2207cf11-c0bb-4826-96c6-61cddfb0e7e8
  REMOVE_JULIAPRO: "true"
  # GitLab requires that the cache path is insde the project
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"

cache:
  paths:
    - .julia/compiled/v1.4
    - html

build:
  stage: build
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - >
      julia --color=yes --project=. -e
      'using Pkg;
       Pkg.instantiate();
       using PumasTutorials;
       PumasTutorials.weave_file("introduction","introduction.jmd",
       (:script,:html,:notebook))'
  artifacts:
    paths:
      - html
    expire_in: 1 week
  only:
  - master
  - tags
  - external
  - pushes

deploy:
  stage: deploy
  script:
    - cp -r html/* public
#     - julia -e 'using InteractiveUtils;
#                 versioninfo()'
#     - julia --color=yes --project -e 'using Pkg;
#                                       using PumasTutorials;
#                                       Pkg.activate(".");
#                                       Pkg.instantiate();'
  only:
  - master
  - tags
  - external
  - pushes
