image: "juliacomputing/juliapro:v1.4.2-1"

variables:
  JULIA_PKG_SERVER: pumas.juliateam.io
  PRIVATE_REGISTRY_NAME: PumasRegistry
  PRIVATE_REGISTRY_UUID: 2207cf11-c0bb-4826-96c6-61cddfb0e7e8
  REMOVE_JULIAPRO: "true"
  # GitLab requires that the cache path is insde the project
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"

cache:
  paths:
    - .julia/compiled/v1.4
    - html

# build:introduction:
#   stage: build
#   script:
#     - julia -e 'using InteractiveUtils;
#                 versioninfo()'
#     - >
#       julia --color=yes --project=. -e
#       'using Pkg;
#        Pkg.instantiate();
#        using PumasTutorials;
#        PumasTutorials.weave_folder("introduction", (:script,:html,))'
#   artifacts:
#     paths:
#       - html
#     expire_in: 1 week
#   only:
#     refs:
#       - external_pull_requests
#     changes:
#       - tutorials/introduction/*

build:pkpd1:
  stage: build
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - >
      julia --color=yes --project=. -e
      'using Pkg;
       Pkg.instantiate();
       using PumasTutorials;
       PumasTutorials.weave_folder("pkpd", (:script,:html,))'
  artifacts:
    paths:
      - html
    expire_in: 1 week
  only:
    refs:
      - external_pull_requests
    changes:
      - tutorials/pkpd/absorption_models.jmd

build:pkpd2:
  stage: build
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - >
      julia --color=yes --project=. -e
      'using Pkg;
       Pkg.instantiate();
       using PumasTutorials;
       PumasTutorials.weave_folder("pkpd", (:script,:html,))'
  artifacts:
    paths:
      - html
    expire_in: 1 week
  only:
    refs:
      - external_pull_requests
    changes:
      - tutorials/pkpd/indirect_response_models.jmd

# .template: &template
#   stage: build
#   script:
#     - julia -e 'using InteractiveUtils;
#                 versioninfo()'
#     - >
#       julia --color=yes --project=. -e
#       'using Pkg;
#        Pkg.instantiate();
#        using PumasTutorials;
#        PumasTutorials.weave_folder("$GROUP", (:script,:html,))'
#   artifacts:
#     paths:
#       - html
#     expire_in: 1 week
#   only:
#     refs:
#       - external_pull_requests
#     changes:
#       - tutorials/$GROUP/*

# build:introduction:
#   <<: *template
#   variables:
#     GROUP: "introduction"

# build:pkpd:
#   <<: *template
#   variables:
#     GROUP: "pkpd"

pages:
  stage: deploy
  script:
    - mkdir public/
    - cp docs/index.html public/
    - cp docs/resources.css public/
    - cp -r html public/
  artifacts:
    paths:
      - public
  only:
  - master
  - tags
  - external_pull_requests
